// Code generated by thriftgo (0.3.3). DO NOT EDIT.

package java

import (
	"reflect"

	"github.com/cloudwego/thriftgo/thrift_reflection"
)

// IDL Name: java
// IDL Path: java.thrift
// Remote Path: github.com/kitex-contrib/codec-dubbo/java

var file_java_thrift *thrift_reflection.FileDescriptor

func init() {
	if file_java_thrift != nil {
		return
	}
	type x struct{}
	replacer := &thrift_reflection.FileDescriptorReplacer{
		RemoteGoPkgPath:  `github.com/kitex-contrib/codec-dubbo/java`,
		CurrentGoPkgPath: reflect.TypeOf(x{}).PkgPath(),
		CurrentFilepath:  `java.thrift`,
		Matcher:          "Object",
	}
	file_java_thrift = thrift_reflection.ReplaceFileDescriptor(replacer)
}

func GetFileDescriptorForJava() *thrift_reflection.FileDescriptor {
	return file_java_thrift
}
