// Code generated by thriftgo (0.3.3). DO NOT EDIT.

package java

import (
	java "github.com/kitex-contrib/codec-dubbo/java"
)

type Object = java.Object

var NewObject = java.NewObject

type Date = java.Date

var NewDate = java.NewDate
