// Code generated by Kitex v0.9.1. DO NOT EDIT.

package greetservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	hello "github.com/kitex-contrib/codec-dubbo/samples/helloworld/kitex/kitex_gen/hello"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Greet(ctx context.Context, req string, callOptions ...callopt.Option) (r string, err error)
	GreetWithStruct(ctx context.Context, req *hello.GreetRequest, callOptions ...callopt.Option) (r *hello.GreetResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kGreetServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGreetServiceClient struct {
	*kClient
}

func (p *kGreetServiceClient) Greet(ctx context.Context, req string, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Greet(ctx, req)
}

func (p *kGreetServiceClient) GreetWithStruct(ctx context.Context, req *hello.GreetRequest, callOptions ...callopt.Option) (r *hello.GreetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GreetWithStruct(ctx, req)
}
