// Code generated by Kitex v0.7.2. DO NOT EDIT.
package greetservice

import (
	server "github.com/cloudwego/kitex/server"
	hello "github.com/kitex-contrib/codec-dubbo/samples/helloworld/kitex/kitex_gen/hello"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello.GreetService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
